name: Python CI

on:
  push:
    branches: [ master ]
    paths:
    - 'app_python/**'
    - '.github/workflows/python-ci.yml'

  pull_request:
    branches: [ master ]
    paths:
    - 'app_python/**'
    - '.github/workflows/python-ci.yml'


jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app_python

    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"

          # Persist uv’s dependency cache between runs
          enable-cache: true

          # Invalidate cache only when *this* project’s deps change
          cache-dependency-glob: |
            app_python/pyproject.toml
            app_python/uv.lock

      
      - name: Install dependencies
        run: uv sync --group test --group lint

      - name: Check formatting
        run: uv run ruff format --check

      - name: Run linter
        run: uv run ruff check

      - name: Run Pyright
        run: uv run pyright
        
      - name: Run Pytest and save coverage report
        run: uv run pytest --cov --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  security:
    needs: test  # ✅ Only run if tests pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"
          enable-cache: true
          cache-dependency-glob: |
            app_python/pyproject.toml
            app_python/uv.lock

      - name: Prepare dependencies for Snyk
        working-directory: app_python
        run: |
          uv sync --frozen
          source .venv/bin/activate
          python -m ensurepip --upgrade
          uv export --locked --format requirements.txt --output-file requirements.txt

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master

      - name: Run Snyk to check for vulnerabilities
        working-directory: app_python
        run: |
          source .venv/bin/activate
          snyk test --file=requirements.txt --severity-threshold=low
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker:
    needs: security  # ✅ Only run if security pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Extract metadata for tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/devops-python-info-service
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha
            type=raw,value={{date 'YYYY.MM' tz='Europe/Kyiv'}}.${{ github.run_number }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./app_python
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
